#ifndef _GET_DQ_H
#define _GET_DQ_H

#define DQ_T	0x00000001
#define DQ_P	0x00000002
#define DQ_s	0x00000004
#define DQ_j1	0x00000008
#define DQ_j2	0x00000010
#define DQ_j3	0x00000020
#define DQ_jabs	0x00000040
#define DQ_kappa	0x00000080
#define DQ_Bc1	0x00000100
#define DQ_Bc2	0x00000200
#define DQ_Bc3	0x00000400
#define DQ_divB	0x00000800
#define DQ_vabs	0x00001000
#define DQ_vh	0x00002000
#define DQ_ekin	0x00004000
#define DQ_plin	0x00008000
#define DQ_vmflux	0x00010000
#define DQ_g1	0x00020000
#define DQ_g3	0x00040000
#define DQ_cs	0x00080000
#define DQ_mach	0x00100000
#define DQ_mmu	0x00200000
#define DQ_tau	0x00400000
#define DQ_Babs	0x00800000
#define DQ_Bh	0x01000000
#define DQ_B2	0x02000000
#define DQ_emag	0x04000000
#define DQ_cA	0x08000000
#define DQ_beta	0x10000000
#define DQ_csca	0x20000000

extern void rhd_dq_init(char* /* parfile */, char* /* modelfile */, \
		int /* nc_p */, int /* imodel */);
extern void get_dq(int /* dq */);

extern int    rhd_dq_box_mp_dq_m1_;
extern int    rhd_dq_box_mp_dq_m2_;
extern int    rhd_dq_box_mp_dq_m3_;
extern int    rhd_dq_box_mp_dq_n1_;
extern int    rhd_dq_box_mp_dq_n2_;
extern int    rhd_dq_box_mp_dq_n3_;
extern float* rhd_dq_box_mp_dq_xb1_;
extern float* rhd_dq_box_mp_dq_xb2_;
extern float* rhd_dq_box_mp_dq_xb3_;
extern float* rhd_dq_box_mp_dq_xc1_;
extern float* rhd_dq_box_mp_dq_xc2_;
extern float* rhd_dq_box_mp_dq_xc3_;
extern float* rhd_dq_box_mp_dq_rho_;
extern float* rhd_dq_box_mp_dq_ei_;
extern float* rhd_dq_box_mp_dq_v1_;
extern float* rhd_dq_box_mp_dq_v2_;
extern float* rhd_dq_box_mp_dq_v3_;
extern float* rhd_dq_box_mp_dq_bb1_;
extern float* rhd_dq_box_mp_dq_bb2_;
extern float* rhd_dq_box_mp_dq_bb3_;
extern float* rhd_dq_box_mp_dq_t_;
extern float* rhd_dq_box_mp_dq_p_;
extern float* rhd_dq_box_mp_dq_s_;
extern float* rhd_dq_box_mp_dq_j1_;
extern float* rhd_dq_box_mp_dq_j2_;
extern float* rhd_dq_box_mp_dq_j3_;
extern float* rhd_dq_box_mp_dq_jabs_;
extern float* rhd_dq_box_mp_dq_kappa_;
extern float* rhd_dq_box_mp_dq_bc1_;
extern float* rhd_dq_box_mp_dq_bc2_;
extern float* rhd_dq_box_mp_dq_bc3_;
extern float* rhd_dq_box_mp_dq_divb_;
extern float* rhd_dq_box_mp_dq_vabs_;
extern float* rhd_dq_box_mp_dq_vh_;
extern float* rhd_dq_box_mp_dq_ekin_;
extern float* rhd_dq_box_mp_dq_plin_;
extern float* rhd_dq_box_mp_dq_vmflux_;
extern float* rhd_dq_box_mp_dq_g1_;
extern float* rhd_dq_box_mp_dq_g3_;
extern float* rhd_dq_box_mp_dq_cs_;
extern float* rhd_dq_box_mp_dq_mach_;
extern float* rhd_dq_box_mp_dq_mmu_;
extern float* rhd_dq_box_mp_dq_tau_;
extern float* rhd_dq_box_mp_dq_babs_;
extern float* rhd_dq_box_mp_dq_bh_;
extern float* rhd_dq_box_mp_dq_b2_;
extern float* rhd_dq_box_mp_dq_emag_;
extern float* rhd_dq_box_mp_dq_ca_;
extern float* rhd_dq_box_mp_dq_beta_;
extern float* rhd_dq_box_mp_dq_csca_;

#define rhd_dq_init_ rhd_dq_module_mp_rhd_dq_init_
#define BOX_m1 rhd_dq_box_mp_dq_m1_
#define BOX_m2 rhd_dq_box_mp_dq_m2_
#define BOX_m3 rhd_dq_box_mp_dq_m3_
#define BOX_n1 rhd_dq_box_mp_dq_n1_
#define BOX_n2 rhd_dq_box_mp_dq_n2_
#define BOX_n3 rhd_dq_box_mp_dq_n3_
#define BOX_xb1 rhd_dq_box_mp_dq_xb1_
#define BOX_xb2 rhd_dq_box_mp_dq_xb2_
#define BOX_xb3 rhd_dq_box_mp_dq_xb3_
#define BOX_xc1 rhd_dq_box_mp_dq_xc1_
#define BOX_xc2 rhd_dq_box_mp_dq_xc2_
#define BOX_xc3 rhd_dq_box_mp_dq_xc3_
#define BOX_rho rhd_dq_box_mp_dq_rho_
#define BOX_ei rhd_dq_box_mp_dq_ei_
#define BOX_v1 rhd_dq_box_mp_dq_v1_
#define BOX_v2 rhd_dq_box_mp_dq_v2_
#define BOX_v3 rhd_dq_box_mp_dq_v3_
#define BOX_T rhd_dq_box_mp_dq_t_
#define BOX_P rhd_dq_box_mp_dq_p_
#define BOX_s rhd_dq_box_mp_dq_s_
#define BOX_j1 rhd_dq_box_mp_dq_j1_
#define BOX_j2 rhd_dq_box_mp_dq_j2_
#define BOX_j3 rhd_dq_box_mp_dq_j3_
#define BOX_jabs rhd_dq_box_mp_dq_jabs_
#define BOX_kappa rhd_dq_box_mp_dq_kappa_
#define BOX_Bc1 rhd_dq_box_mp_dq_bc1_
#define BOX_Bc2 rhd_dq_box_mp_dq_bc2_
#define BOX_Bc3 rhd_dq_box_mp_dq_bc3_
#define BOX_divB rhd_dq_box_mp_dq_divb_
#define BOX_vabs rhd_dq_box_mp_dq_vabs_
#define BOX_vh rhd_dq_box_mp_dq_vh_
#define BOX_ekin rhd_dq_box_mp_dq_ekin_
#define BOX_plin rhd_dq_box_mp_dq_plin_
#define BOX_vmflux rhd_dq_box_mp_dq_vmflux_
#define BOX_g1 rhd_dq_box_mp_dq_g1_
#define BOX_g3 rhd_dq_box_mp_dq_g3_
#define BOX_cs rhd_dq_box_mp_dq_cs_
#define BOX_mach rhd_dq_box_mp_dq_mach_
#define BOX_mmu rhd_dq_box_mp_dq_mmu_
#define BOX_tau rhd_dq_box_mp_dq_tau_
#define BOX_Babs rhd_dq_box_mp_dq_babs_
#define BOX_Bh rhd_dq_box_mp_dq_bh_
#define BOX_B2 rhd_dq_box_mp_dq_b2_
#define BOX_emag rhd_dq_box_mp_dq_emag_
#define BOX_cA rhd_dq_box_mp_dq_ca_
#define BOX_beta rhd_dq_box_mp_dq_beta_
#define BOX_csca rhd_dq_box_mp_dq_csca_

#endif /* get_dq.h */
