#ifndef _GET_DQ_H
#define _GET_DQ_H

#define DQ_T	0x00000001
#define DQ_P	0x00000002
#define DQ_s	0x00000004
#define DQ_j1	0x00000008
#define DQ_j2	0x00000010
#define DQ_j3	0x00000020
#define DQ_jabs	0x00000040
#define DQ_kappa	0x00000080
#define DQ_Bc1	0x00000100
#define DQ_Bc2	0x00000200
#define DQ_Bc3	0x00000400
#define DQ_divB	0x00000800
#define DQ_vabs	0x00001000
#define DQ_vh	0x00002000
#define DQ_ekin	0x00004000
#define DQ_plin	0x00008000
#define DQ_vmflux	0x00010000
#define DQ_g1	0x00020000
#define DQ_g3	0x00040000
#define DQ_cs	0x00080000
#define DQ_mach	0x00100000
#define DQ_mmu	0x00200000
#define DQ_tau	0x00400000
#define DQ_Babs	0x00800000
#define DQ_Bh	0x01000000
#define DQ_B2	0x02000000
#define DQ_emag	0x04000000
#define DQ_cA	0x08000000
#define DQ_beta	0x10000000
#define DQ_csca	0x20000000

extern void rhd_dq_init(char* /* parfile */, char* /* modelfile */, \
		int /* nc_p */, int /* imodel */);
extern void get_dq(int /* dq */);

extern int    __rhd_dq_box_MOD_dq_m1;
extern int    __rhd_dq_box_MOD_dq_m2;
extern int    __rhd_dq_box_MOD_dq_m3;
extern int    __rhd_dq_box_MOD_dq_n1;
extern int    __rhd_dq_box_MOD_dq_n2;
extern int    __rhd_dq_box_MOD_dq_n3;
extern float* __rhd_dq_box_MOD_dq_xb1;
extern float* __rhd_dq_box_MOD_dq_xb2;
extern float* __rhd_dq_box_MOD_dq_xb3;
extern float* __rhd_dq_box_MOD_dq_xc1;
extern float* __rhd_dq_box_MOD_dq_xc2;
extern float* __rhd_dq_box_MOD_dq_xc3;
extern float* __rhd_dq_box_MOD_dq_rho;
extern float* __rhd_dq_box_MOD_dq_ei;
extern float* __rhd_dq_box_MOD_dq_v1;
extern float* __rhd_dq_box_MOD_dq_v2;
extern float* __rhd_dq_box_MOD_dq_v3;
extern float* __rhd_dq_box_MOD_dq_bb1;
extern float* __rhd_dq_box_MOD_dq_bb2;
extern float* __rhd_dq_box_MOD_dq_bb3;
extern float* __rhd_dq_box_MOD_dq_t;
extern float* __rhd_dq_box_MOD_dq_p;
extern float* __rhd_dq_box_MOD_dq_s;
extern float* __rhd_dq_box_MOD_dq_j1;
extern float* __rhd_dq_box_MOD_dq_j2;
extern float* __rhd_dq_box_MOD_dq_j3;
extern float* __rhd_dq_box_MOD_dq_jabs;
extern float* __rhd_dq_box_MOD_dq_kappa;
extern float* __rhd_dq_box_MOD_dq_bc1;
extern float* __rhd_dq_box_MOD_dq_bc2;
extern float* __rhd_dq_box_MOD_dq_bc3;
extern float* __rhd_dq_box_MOD_dq_divb;
extern float* __rhd_dq_box_MOD_dq_vabs;
extern float* __rhd_dq_box_MOD_dq_vh;
extern float* __rhd_dq_box_MOD_dq_ekin;
extern float* __rhd_dq_box_MOD_dq_plin;
extern float* __rhd_dq_box_MOD_dq_vmflux;
extern float* __rhd_dq_box_MOD_dq_g1;
extern float* __rhd_dq_box_MOD_dq_g3;
extern float* __rhd_dq_box_MOD_dq_cs;
extern float* __rhd_dq_box_MOD_dq_mach;
extern float* __rhd_dq_box_MOD_dq_mmu;
extern float* __rhd_dq_box_MOD_dq_tau;
extern float* __rhd_dq_box_MOD_dq_babs;
extern float* __rhd_dq_box_MOD_dq_bh;
extern float* __rhd_dq_box_MOD_dq_b2;
extern float* __rhd_dq_box_MOD_dq_emag;
extern float* __rhd_dq_box_MOD_dq_ca;
extern float* __rhd_dq_box_MOD_dq_beta;
extern float* __rhd_dq_box_MOD_dq_csca;

#define rhd_dq_init rhd_dq_init
#define BOX_m1 __rhd_dq_box_MOD_dq_m1
#define BOX_m2 __rhd_dq_box_MOD_dq_m2
#define BOX_m3 __rhd_dq_box_MOD_dq_m3
#define BOX_n1 __rhd_dq_box_MOD_dq_n1
#define BOX_n2 __rhd_dq_box_MOD_dq_n2
#define BOX_n3 __rhd_dq_box_MOD_dq_n3
#define BOX_xb1 __rhd_dq_box_MOD_dq_xb1
#define BOX_xb2 __rhd_dq_box_MOD_dq_xb2
#define BOX_xb3 __rhd_dq_box_MOD_dq_xb3
#define BOX_xc1 __rhd_dq_box_MOD_dq_xc1
#define BOX_xc2 __rhd_dq_box_MOD_dq_xc2
#define BOX_xc3 __rhd_dq_box_MOD_dq_xc3
#define BOX_rho __rhd_dq_box_MOD_dq_rho
#define BOX_ei __rhd_dq_box_MOD_dq_ei
#define BOX_v1 __rhd_dq_box_MOD_dq_v1
#define BOX_v2 __rhd_dq_box_MOD_dq_v2
#define BOX_v3 __rhd_dq_box_MOD_dq_v3
#define BOX_T __rhd_dq_box_MOD_dq_t
#define BOX_P __rhd_dq_box_MOD_dq_p
#define BOX_s __rhd_dq_box_MOD_dq_s
#define BOX_j1 __rhd_dq_box_MOD_dq_j1
#define BOX_j2 __rhd_dq_box_MOD_dq_j2
#define BOX_j3 __rhd_dq_box_MOD_dq_j3
#define BOX_jabs __rhd_dq_box_MOD_dq_jabs
#define BOX_kappa __rhd_dq_box_MOD_dq_kappa
#define BOX_Bc1 __rhd_dq_box_MOD_dq_bc1
#define BOX_Bc2 __rhd_dq_box_MOD_dq_bc2
#define BOX_Bc3 __rhd_dq_box_MOD_dq_bc3
#define BOX_divB __rhd_dq_box_MOD_dq_divb
#define BOX_vabs __rhd_dq_box_MOD_dq_vabs
#define BOX_vh __rhd_dq_box_MOD_dq_vh
#define BOX_ekin __rhd_dq_box_MOD_dq_ekin
#define BOX_plin __rhd_dq_box_MOD_dq_plin
#define BOX_vmflux __rhd_dq_box_MOD_dq_vmflux
#define BOX_g1 __rhd_dq_box_MOD_dq_g1
#define BOX_g3 __rhd_dq_box_MOD_dq_g3
#define BOX_cs __rhd_dq_box_MOD_dq_cs
#define BOX_mach __rhd_dq_box_MOD_dq_mach
#define BOX_mmu __rhd_dq_box_MOD_dq_mmu
#define BOX_tau __rhd_dq_box_MOD_dq_tau
#define BOX_Babs __rhd_dq_box_MOD_dq_babs
#define BOX_Bh __rhd_dq_box_MOD_dq_bh
#define BOX_B2 __rhd_dq_box_MOD_dq_b2
#define BOX_emag __rhd_dq_box_MOD_dq_emag
#define BOX_cA __rhd_dq_box_MOD_dq_ca
#define BOX_beta __rhd_dq_box_MOD_dq_beta
#define BOX_csca __rhd_dq_box_MOD_dq_csca

#endif /* get_dq.h */
